baseurl = "https://openr.pzhao.org/"
title = "Open R"
theme = "hugo-universal-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "pzhao"

[languages.en]
  languageCode = "en-us"

[languages.zh]
  languageCode = "zh-cn"

  # Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-157880803-1"

# Define the number of posts per page
paginate = 10

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

[[menu.main]]
    name = "Book"
    url  = "/zh/tags/xuer/"
    weight = 5

[[menu.main]]
    name = "中文"
    url  = "/zh/"
    weight = 6

[[languages.zh.menu.main]]
    name = "主页"
    url  = "/zh/"
    weight = 1

[[languages.zh.menu.main]]
    name = "博客"
    url  = "/zh/blog/"
    weight = 2

[[languages.zh.menu.main]]
    name = "常见问题"
    identifier = "faq"
    url  = "/zh/faq/"
    weight = 3

[[languages.zh.menu.main]]
    name = "联系我们"
    url  = "/zh/contact/"
    weight = 4

[[languages.zh.menu.main]]
    name = "学 R"
    url  = "/zh/tags/xuer/"
    weight = 5

[[languages.zh.menu.main]]
    name = "EN"
    url  = "/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 10
    name = "RSS"
    url = "/index.xml"
    pre = "<i class='fa fa-2x fa-rss'></i>"

[[languages.zh.menu.topbar]]
    weight = 10
    name = "RSS"
    url = "/zh/index.xml"
    pre = "<i class='fa fa-2x fa-rss'></i>"

[[menu.topbar]]
    weight = 20
    name = "GitHub"
    url = "https://github.com/rbind/openr"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[languages.zh.menu.topbar]]
    weight = 20
    name = "GitHub"
    url = "https://github.com/rbind/openr"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 30
    name = "Email"
    url = "mailto:openr@pzhao.net"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[[languages.zh.menu.topbar]]
    weight = 30
    name = "Email"
    url = "mailto:openr@pzhao.net"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
#    author = "DevCows"
#    defaultKeywords = ["devows", "hugo", "go"]
#    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
  #  email = "baydap@gmail.com"

    about_us = "<p>We are one.</p>"
    copyright = "Copyright (c) 2019, OpenR Team; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo-small.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong><a href='mailto:openr@pzhao.net'>OpenR Team</a></strong>
      </p>
      """

 #   latitude = "-12.043333"
  #  longitude = "-77.028333"

[languages.zh.params]
    viewMorePostLink = "/zh/blog/"
#    author = "DevCows"
#    defaultKeywords = ["devows", "hugo", "go"]
#    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
#    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
 #   email = "baydap@gmail.com"

    about_us = "<p>我们就是我们。</p>"
    copyright = "Copyright (c) 2019, OpenR Team; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>OpenR Team</strong>
      </p>
      """
#    latitude = "-12.043333"
#    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:slug/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us by subscribing RSS, on github, or via email.</p>
      <p class="hidden-md hidden-lg">
      </p>
      """

[languages.zh.params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">通过 github 或电子邮件联系我们.</p>
      <p class="hidden-md hidden-lg">
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = true

[languages.zh.params.widgets]
    categories = false
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[languages.zh.params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "评价"
    subtitle = "这里是我们的热心读者和用户留下的反馈。"

[params.see_more]
    enable = true
    icon = "fa fa-book"
    title = "Do you want to see more?"
    subtitle = "Please visit the homepage of the book Learning R."
    link_url = "https://xuer.pzhao.org/"
    link_text = "Learning R"

[languages.zh.params.see_more]
    enable = true
    icon = "fa fa-book"
    title = "您想了解更多吗？"
    subtitle = "请访问《学 R》一书的网站。"
    link_url = "https://xuer.pzhao.org/"
    link_text = "学 R"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Team"
    subtitle = ""

[languages.zh.params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "我们的团队"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "News about everyhing of us."

[languages.zh.params.recent_posts]
    enable = true
    title = "最新博客"
    subtitle = "新闻，动向，教程。更多博客请点击[这里](/zh/blog/)或右上角的“博客”。"

[blackfriday]
smartypants = false
